### ISSUE TITLE
Failing tests on i386

### ISSUE THREAD

**Issue by aviau** [vmihailenco/msgpack#101]
Hello,

Debian is getting failing tests on i386.

```
src/gopkg.in/vmihailenco/msgpack.v2/bench_test.go:81: constant 2147483648 overflows in
```

Full log: https://tests.reproducible-builds.org/debian/rb-pkg/testing/i386/golang-gopkg-vmihailenco-msgpack.v2.html

**Comment by vmihailenco** [comment]
Thanks for the report. I release v2.7.1 with the fix and added i386 build so this does not happen in future.
