### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by hlandau** [vmihailenco/msgpack#103]
Your package depends on github.com/ugorji/go-msgpack which is deprecated and in turn depends on a package launchpad.net/mgo/bson which has moved to `https://gopkg.in/mgo.v2`, so the dependency chain is now broken. I've created issue https://github.com/ugorji/go-msgpack/issues/16 but maybe this package should considering moving to ugorji/go-msgpack's successor instead?

**Comment by vmihailenco** [comment]
That dependency exists only if you want to run benchmarks/tests. Package itself does not have any benchmarks. I will consider moving benchmarks to separate package.

**Comment by hlandau** [comment]
Indeed. But it's nonetheless a broken dependency and it's breaking some vendorization tools. Either way, the benchmarks/tests are broken...

**Comment by vmihailenco** [comment]
Thanks for bringing this - I was not aware of the issue. Fixed in v2.7.2
