### ISSUE TITLE
Add ability to pack/unpack struct as an array

### ISSUE THREAD

**Issue by funny-falcon** [vmihailenco/msgpack#110]
We use this package for connector to in-memory database [tarantool](https://tarantool.org) .
Tarantool uses msgpack arrays for its row types.
Pack/unpack from a struct to msgpack array currently ought to go through CustomEncoder/CustomDecoder.

Proposal is to add ability to point that struct should be packed/unpacked as an array without need for CustomEncoder/Decoder.

ugorji/codec provides this ability through tags on specific field: https://godoc.org/github.com/ugorji/go/codec#Encoder.Encode

> However, struct values may encode as arrays. This happens when:
> - StructToArray Encode option is set, OR
> - the tag on the _struct field sets the "toarray" option

**Comment by vmihailenco** [comment]
Can you please provide some code that uses Tarantool and CustomEncoder/CustomDecoder? Thanks.

**Comment by funny-falcon** [comment]
Simple example is in tests:
https://github.com/tarantool/go-tarantool/blob/master/tarantool_test.go#L31-L59

In real life, array len could differs from number of fields (cause of schema migration: row version for previous schema could contain less fields, and row for next schema version could contain more fields).

**Comment by vmihailenco** [comment]
So what behavior do you expect from this lib when number of rows don't match?

**Comment by vmihailenco** [comment]
Please take a look at https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#Encoder.StructAsArray and let me know if something is missing. Currently code just ignores missing/extra fields.

**Comment by funny-falcon** [comment]
It is mostly ok. You forgot to skip extra array values.

I think, it is better to decode array to struct only if it has 'asArray' tag (or StructAsArray flag is set on decoder). I think, it will be unexpected for most users if array will be unpacked to struct without any directive to do it. But it just my opinion, I could be mistaken.

**Comment by vmihailenco** [comment]
>You forgot to skip extra array values.

Thanks - fixing.

>I think, it will be unexpected for most users if array will be unpacked to struct without any directive to do it.

Since we have `StructAsArray` flag that allows switching between 2 modes I *think* that we should accept both variants...

**Comment by funny-falcon** [comment]
So, may be add similar instruction to decoder? `Decoder.AllowStructAsArray(bool)` . If it is set, then every struct could be unpacked from array. If it is not set, then only structs with `asArray` tag could be unpacked from array. What do you think?

**Comment by vmihailenco** [comment]
>What do you think?

I had it at some point but
- it is extra API (Decoder.AllowStructAsArray)
- extra code (not much, but there are a lot of conditions already)
- does not add much value, because Decoder does not provide any guarantees that decoded struct is valid (has all fields initialized)

So unless there is a practical reason I'd rather not add it.

**Comment by funny-falcon** [comment]
Ok, I have no more arguments to defend my position :-) time will show.

Big thanks for adding this feature!

**Comment by vmihailenco** [comment]
You are welcome :)
