### ISSUE TITLE
nested map[string]interface{} encode/decode problem

### ISSUE THREAD

**Issue by elhussein-ali** [vmihailenco/msgpack#117]
i notice the following
the encoding for a nested map[string]interface{} type then decoding it
it give me a map of type map[interface{}]interface{}
which led me to be non json compatible

is that right for msgpack spec. or what?

**Comment by vmihailenco** [comment]
msgpack decoder does not know the type of the map so it assumes the worst - `map[interface{}]interface{}`. See https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#example-Marshal--MapStringInterface

**Comment by elhussein-ali** [comment]
thank

but is it available while decoding the map to check the keys type if all the keys of type string
then the decoder convert it to type map[string]interface{} rather than map[interface{}]ineterface{}

**Comment by vmihailenco** [comment]
That means a lot of overhead
- decode all keys and values into temporal storage
- check keys types
- create map of right type and copy data from temporal storage

**Comment by elhussein-ali** [comment]
yes i known it will be overhead
but is it available to be optional parameter (true or false) into Unmarshal method

for example

```
  var result interface{}
  err := msgpack.Unmarshal(data, &result, true /* correct the map type */)
```

thanks again for reply

**Comment by vmihailenco** [comment]
It is possible, but then you should check if you got `map[string]interface{}` or `map[interface{}]interface{}` or whatever.

**Comment by elhussein-ali** [comment]
you are right

but in my use-case scenario my type checking will make me reject or accept the return type if it is not a map[string]interface{}

thanks again
