### ISSUE TITLE
Export EncodeBytesLen() in the encoder

### ISSUE THREAD

**Issue by xichen2020** [vmihailenco/msgpack#119]
Is it possible to export `EncodeBytesLen()` in the encoder APIs? My use case is that I need to encode a large number of items, each of which contains an ID, which in turn contains a prefix, a body, and a suffix, all of which are byte slices, e.g.,
```
type ID struct {
  Prefix []byte
  Body []byte
  Suffix []byte
}
```

What I'd like to achieve is to encode the `ID` object as if it were a single `[]byte` so that I can avoid unnecessary byte copies during decoding. With the existing API, I'd have to concatenate the prefix/body/suffix and create a new byte slice to use the `EncodeBytes` method. However if we export `EncodeBytesLen()`, I can call `EncodeBytesLen()` to encode the number of bytes first, then write the raw bytes.

If that sounds reasonable, I'd be happy to put up a PR.

**Comment by vmihailenco** [comment]
Bytes is a slice (array) so you use [EncodeArrayLen](https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#Encoder.EncodeArrayLen).

**Comment by vmihailenco** [comment]
Hm, no - I am wrong. Please send a PR.

**Comment by xichen2020** [comment]
Here it is: https://github.com/vmihailenco/msgpack/pull/120
