### ISSUE TITLE
List this projects on msgpack.org

### ISSUE THREAD

**Issue by funny-falcon** [vmihailenco/msgpack#122]
Instruction: https://github.com/msgpack/website/blob/master/README.md#how-to-list-up-your-project-on-msgpackorg

**Comment by vmihailenco** [comment]
Added msgpack.org[Go] to the description. Let's see if it works.

**Comment by vmihailenco** [comment]
No luck so far and I don't see what is missing...

**Comment by vmihailenco** [comment]
It seems to be fixed after making master branch the default.
