### ISSUE TITLE
Expose Write()/WriteByte()/WriteString() to Encoder (and similar for Decoder?)

### ISSUE THREAD

**Issue by lestrrat** [vmihailenco/msgpack#127]
I'm trying to encode/decode an extension, namely https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#eventtime-ext-format

If my understanding is correct, to implement this you need to the ability to write raw bytes to the underlying io.Writer instead of using EncodeInt8, EncodeInt32, etc. But currently the capability to do this is in `Encoder.w`, which is no exposed to end users.

Should this be exposed? or is there a better way to do this?

**Comment by vmihailenco** [comment]
I've released v2.9.0 with some fixes and better example - https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#example-RegisterExt

**Comment by lestrrat** [comment]
Thanks, read the docs, and made sense!
