### ISSUE TITLE
package github.com/vmihailenco/bufio: exit status 128

### ISSUE THREAD

**Issue by mausquirk** [vmihailenco/msgpack#141]
Hi, 
Sorry to bother you on this repository. 
I'm trying to compile https://github.com/shirou/mqforward which finally depends on the non-existing `github.com/vmihailenco/bufio` repository.  I assume, that your code made it into the official go-language repository.

go get fails with: 

```
 go get
# cd .; git clone https://github.com/vmihailenco/bufio /home/xy/opt/go/src/github.com/vmihailenco/bufio
Klone nach '/home/xy/opt/go/src/github.com/vmihailenco/bufio' ...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/vmihailenco/bufio: exit status 128
```

I 'm new to go and can't really figure out which package refers to the non-existing repository. Do you have a recommendations on how I could  break up this dependency?

**Comment by vmihailenco** [comment]
Hi,

I just restored https://github.com/vmihailenco/bufio from old copy. Hopefully it fixes the issue.

The proper fix would be to replace `gopkg.in/vmihailenco/msgpack.v1` with `github.com/vmihailenco/msgpack` in https://github.com/shirou/mqforward/blob/master/message.go#L6. I think no other changes would be needed.
