### ISSUE TITLE
msgpack packs int but decodes as uint64.

### ISSUE THREAD

**Issue by elico** [vmihailenco/msgpack#142]
I a using msgpack to encode a map ie:
newmap["rate"] = 100
marshalledMap, _ := msgpack.Marshal(newmap)
var valOut map[string]interface{}
_ = msgpack.Unmarshal(marshalledMap, &valOut)
reflect.TypeOf(valOut["rate"])
>> uint64

it should be packed as int or int64 and back it int or int64, not uint64.

Example where it persists with json encoding end decoding but not with msgpack.
https://play.golang.org/p/VaeYnkLPS3

**Comment by vmihailenco** [comment]
What happens is that msgpack packs number `10444440` as uint32, because it fits into 4 bytes. Smaller numbers can be encoded as uint16 or even uint8. Negative numbers can be encoded as int8/16/32/64. It is a bit inconvenient that your code should be prepared to accept all flavors of ints, but you decode into `interface{}` so type is not defined.

We could introduce some option to decode numbers into interface{} only as `int64/uint64`, but I am not sure it is widely usable...

**Comment by elico** [comment]
@vmihailenco thanks for responding!.
I was thinking about the right approach and have seen that some numbers end up as uint8 or int8.
I wrote a "all to int" function:
```
func msgPackPackedIntToInt(unpacked map[string]interface{}, valueName string) int {
	switch rateType := unpacked[valueName].(type) {
	case int:
		return int(unpacked[valueName].(int))
	case int8:
		return int(unpacked[valueName].(int8))
	case int16:
		return int(unpacked[valueName].(int16))
	case int32:
		return int(unpacked[valueName].(int32))
	case uint:
		return int(unpacked[valueName].(uint))
	case uint8:
		return int(unpacked[valueName].(uint8))
	case uint16:
		return int(unpacked[valueName].(uint16))
	case uint32:
		return int(unpacked[valueName].(uint32))
	case uint64:
		return int(unpacked[valueName].(uint64))
	case int64:
		return int(unpacked[valueName].(int64))
	case float32:
		return int(unpacked[valueName].(float32))
	case float64:
		return int(unpacked[valueName].(float64))
	default:
		if *debug {
			fmt.Println("Rate type else =>", rateType)
		}
	}
	return 0
}
```
it takes any other type on int or uint and convert into int.
since the issue is with a specific scenario which the map has a structure of: map[string]interface{}
The function gives the programmer the option to choose a specific field to "digest".
I have seen that json and yaml are doing it a bit different and I do like the way msgpack does things from other angles such as performance.
For now since I have a solution the first thing is that the issue is written and known.
Is it briefly documented somewhere that I missed?
If not. Can you please document it somewhere? maybe on the Decode and Marshal functions?

**Comment by vmihailenco** [comment]
There is a list of types returned by DecodeInterface - http://godoc.org/github.com/vmihailenco/msgpack#Decoder.DecodeInterface. I will add some docs about numbers to Encoder too.

**Comment by elico** [comment]
> @vmihailenco In the docs it states:
> 
> > DecodeInterface decodes value into interface. Possible value types are: ...

But from a basic reading it looks to me like it's possible to **use** one of these types and nothing is mentioned about the "automatic" choice which can be described with something like:

> The encoder will choose the "best" option from the list based on X or  Y or Z
> And it is not guaranteed that if you encoded int it will be encoded and decoded as int but can be one of the mentioned types.
> For more details dive into the sources.

**Comment by vmihailenco** [comment]
Yeah, that is what I want to add to the Encoder docs.

**Comment by elico** [comment]
@vmihailenco OK, Thanks.
I must take the opportunity to say big thanks for the library.
It's helping me a lot!!

**Comment by viciious** [comment]
> We could introduce some option to decode numbers into interface{} only as int64/uint64, but I am not sure it is widely usable...

That would be great feature! The necessity to support all possible int variations via type switching is a real pain...

**Comment by elico** [comment]
@viciious I don't know the cost of CPU and other things for this specific "switch case" but it's very simple to use and very fast for a server while for other platforms it might not be this way.

**Comment by viciious** [comment]
@elico it's not about performance, it's about convenience and keeping your code sane. The ambiguity of decoded integer fields makes it impossible to use them as indexes to arrays and maps or return values for functions.

Some schema-less key-value storage engines such as Tarantool use msgpack to encode and decode tuple fields. To illustrate, imagine you had to individually deduct the type for integer field in each mysql row in the result set depending on how large the value is. That would be insane.

In my opinion there is absolutely no practical reason to use integers of size less than 64 bits after the decoding stage.

**Comment by elico** [comment]
@viciious I am almost sure it depends on the target machines and software.
The msgpack code has not committed in any way I see to preserve the input int\uint type and compared to yaml or json I would expect it to be consistent.
But when I look into what and where msgpack is used I kind of understand that it's not the same as a mysql row but it still a bit insane to expect the same encoder and decoder to digest differently the same content.
When I am looking at it compared to json or yaml or other formats I see a different in the "orientation" of the format encoding and decoding.
I believe that you can try to compare json or yaml to msgpack but not mysql or any other "static" based format nature.

I do see the conflict when you are used to a static language such as GoLang and I would expect the author( @vmihailenco  ) to supply something that will try to help the target audience to feel more "static" and in the upper levels of programming rather then feeling on the wire the "bits".

I can think about a decode option that will "guide" the default of a uint64\int64 compared to something that might look or act like a "random" one which is based on bits.

**Comment by viciious** [comment]
@elico This was my understanding as well. I think an option to uniformly decode all integers to 64bit types would be the best non-disruptive solution. I'll open a separate issue for that. Thanks!
