### ISSUE TITLE
An option to uniformly decode all integers to 64bit types

### ISSUE THREAD

**Issue by viciious** [vmihailenco/msgpack#144]
This is somewhat a continuation of discussion that first took place in #142. Since go is a statically typed language, using msgpack is very inconvenient at the moment because one has to use type switching to be able to use integer fields after decoding. It would be great if there was a decoder option to "upscale" all integer (and probably float) types to 64 bits so the programmer wouldn't have to worry about specific types at the upper level.

**Comment by vmihailenco** [comment]
Done, though such up-scaling can be done in user space too.

**Comment by viciious** [comment]
Great, thanks!
