### ISSUE TITLE
Invalid timestamp serialization

### ISSUE THREAD

**Issue by frekw** [vmihailenco/msgpack#146]
Hi!

According to the spec, timestamps, when serialized as 96 bits, should use a **signed** int for the the 64 bits representing the seconds. However, https://github.com/vmihailenco/msgpack/blob/master/time.go#L47 seems to encode the `seconds` part of the timestamp as an unsigned int.

**Comment by vmihailenco** [comment]
AFAIK there is no real difference between encoding int64 and uint64. Do you have a test case that is affected by this?

**Comment by frekw** [comment]
You're absolutely right. It was the library that I was interfacing with that was dealing with it incorrectly. Sorry!
