### ISSUE TITLE
What ascii code should I use as delimeter?

### ISSUE THREAD

**Issue by atsushi-ishibashi** [vmihailenco/msgpack#148]
Server encodes struct to []byte and sends on tcp stream. Client receives data stream and decodes to struct.
I'm using 0x02 as start delim and 0x03 as end delim, but I found these two bytes are used in encoded data bytes.
Are there anyone who could teach which ascii code will never be used in encoded data?
Or should I add the length of the data?

**Comment by vmihailenco** [comment]
The list of msgpack codes can be found in https://github.com/vmihailenco/msgpack/blob/master/codes/codes.go. But overall any byte can be found in msgpack data. I would just use msgpack without any special tricks.

**Comment by atsushi-ishibashi** [comment]
Thank you🙇 
I will choose the method of adding length of data.
