### ISSUE TITLE
msgpack: invalid code=cd decoding bytes length

### ISSUE THREAD

**Issue by xpemail** [vmihailenco/msgpack#156]
msgpack: invalid code=cd decoding bytes length

**Comment by vmihailenco** [comment]
Please write a program that reproduces the issue.

**Comment by xpemail** [comment]
dat, err := ioutil.ReadFile("/data1/x.txt")
v := make(map[string]map[string][]int64)
err := msgpack.Unmarshal(dat, &v, nil)

// dat is encoding by msgpack-php 
// json data like this:
 {"21111":{"11":[0]},"21112":{"12":[1],"13":[1511169079]}}

**Comment by vmihailenco** [comment]
That is not a program that can be run to reproduce the problem.

**Comment by xpemail** [comment]
[x.txt](https://github.com/vmihailenco/msgpack/files/1490394/x.txt)

**Comment by xpemail** [comment]
x.txt is packed by msgpack-php , but can not be unpacked. 
err: msgpack: invalid code=cd decoding bytes length

**Comment by xpemail** [comment]
it is not a bug, in php the map key string auto convert to int .
