### ISSUE TITLE
Socket.oi redis

### ISSUE THREAD

**Issue by ramonberrutti** [vmihailenco/msgpack#163]
(THIS IS NOT A BUG)
Hi, I'm using your go redis lib, to get msg.
I subscribe to some redis channels that are publish by the redis adapter.

Well, redis send a pack that is an array.
Now the big question,  need decode this array, I try with [] and I decode without problem that array, the problem is the sub array, how I can do?
Any tips?

Now I get working with decode Query, but not is a nice solution I think

**Comment by vmihailenco** [comment]
I am not sure I follow, but the only option I see is to decode into `[]interface{}` slice and then check type of every element in the slice.

**Comment by ramonberrutti** [comment]
thanks @vmihailenco .
The first content of the array that is a string if working, but the other struct that are also arrays don't.
I think that implementing my own decoded work better, also inside the second array is another array.

This is an example of json decoed:
`[
  "mDjtwg",
  {
    "type": 2,
    "data": [
      "gameLobbyAction",
      {
        "idplayer": "390486",
        "action": "setPlayerReady",
        "date": {
          "buffer": {
            "type": "Buffer",
            "data": [
              0,
              0,
              1,
              96,
              29,
              196,
              26,
              136
            ]
          },
          "type": 0
        }
      }
    ],
    "nsp": "/"
  },
  {
    "rooms": [
      "gameRoomID2006876"
    ],
    "flags": {}
  }
]`
