### ISSUE TITLE
indirection through nil pointer to

### ISSUE THREAD

**Issue by indie21** [vmihailenco/msgpack#167]
panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
reflect.Value.FieldByIndex(0x1b92180, 0xc4204dd220, 0x199, 0xc427b53e60, 0x2, 0x2, 0x8, 0x0, 0x100ddd2)
        /usr/local/go/src/reflect/value.go:804 +0x26f
oops/vendor/github.com/vmihailenco/msgpack.(*field).value(0xc422e4ff80, 0x1b92180, 0xc4204dd220, 0x199, 0x0, 0xc420848b60, 0x0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/types.go:81 +0x5f
oops/vendor/github.com/vmihailenco/msgpack.(*field).DecodeValue(0xc422e4ff80, 0xc427ea6120, 0x1b92180, 0xc4204dd220, 0x199, 0xc422b7d518, 0x10c3054)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/types.go:93 +0x4d
oops/vendor/github.com/vmihailenco/msgpack.decodeStructValue(0xc427ea6120, 0x1b92180, 0xc4204dd220, 0x199, 0xc4204dd220, 0x199)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode_map.go:258 +0x425
oops/vendor/github.com/vmihailenco/msgpack.ptrDecoderFunc.func1(0xc427ea6120, 0x1a96fc0, 0xc43548eb88, 0x196, 0x1a96fc0, 0x97)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode_value.go:121 +0xc3
oops/vendor/github.com/vmihailenco/msgpack.(*Decoder).DecodeValue(0xc427ea6120, 0x1a96fc0, 0xc43548eb88, 0x196, 0x1a96fc0, 0xc43548eb88)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode.go:201 +0x8c
oops/vendor/github.com/vmihailenco/msgpack.decodeSliceValue(0xc427ea6120, 0x1aae2a0, 0xc427eaae18, 0x197, 0x1aae2a0, 0xc427eaae18)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode_slice.go:110 +0x1bb
oops/vendor/github.com/vmihailenco/msgpack.(*field).DecodeValue(0xc422e4fcc0, 0xc427ea6120, 0x1c4ff40, 0xc427eaade8, 0x199, 0x0, 0x0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/types.go:93 +0x82
oops/vendor/github.com/vmihailenco/msgpack.decodeStructValue(0xc427ea6120, 0x1c4ff40, 0xc427eaade8, 0x199, 0x1c4ff40, 0x0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode_map.go:258 +0x425
oops/vendor/github.com/vmihailenco/msgpack.(*Decoder).DecodeValue(0xc427ea6120, 0x1c4ff40, 0xc427eaade8, 0x199, 0x1c4ff40, 0xc427eaade8)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode.go:201 +0x8c
oops/vendor/github.com/vmihailenco/msgpack.decodeSliceValue(0xc427ea6120, 0x1ab7020, 0xc42047a0f0, 0x197, 0x1ab7020, 0xc42047a0f0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode_slice.go:110 +0x1bb
oops/vendor/github.com/vmihailenco/msgpack.(*field).DecodeValue(0xc422e4e9c0, 0xc427ea6120, 0x1c995a0, 0xc42047a0c0, 0x199, 0x0, 0x0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/types.go:93 +0x82
oops/vendor/github.com/vmihailenco/msgpack.decodeStructValue(0xc427ea6120, 0x1c995a0, 0xc42047a0c0, 0x199, 0x1c995a0, 0xc42047a0c0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode_map.go:258 +0x425
oops/vendor/github.com/vmihailenco/msgpack.(*Decoder).DecodeValue(0xc427ea6120, 0x1c995a0, 0xc42047a0c0, 0x199, 0xc42047a0c0, 0x199)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode.go:201 +0x8c
oops/vendor/github.com/vmihailenco/msgpack.(*Decoder).decode(0xc427ea6120, 0x1a97100, 0xc42047a0c0, 0x1b5f1e0, 0x1c3c840)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode.go:196 +0x11c
oops/vendor/github.com/vmihailenco/msgpack.(*Decoder).Decode(0xc427ea6120, 0xc422b7db58, 0x1, 0x1, 0xc43548d2f0, 0x1)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode.go:82 +0x6f
oops/vendor/github.com/vmihailenco/msgpack.Unmarshal(0xc4349a2000, 0x1c58e, 0x1c58e, 0xc422b7db58, 0x1, 0x1, 0x0, 0x0)
        /Users/zhuoyikang/source/go/src/oops/vendor/github.com/vmihailenco/msgpack/decode.go:36 +0x230

did you meet this crash before, i am working on it.

**Comment by indie21** [comment]
it's very easy to crash
consider it as a bug


type MsgTest1 struct {
	A int32
}

type MsgTest2 struct {
	*MsgTest1
	B int32
}

func TestMsgPack(t *testing.T) {

	t1 := &MsgTest2{nil, 2}
	t2 := &MsgTest2{}
	bytes, err := msgpack.Marshal(t1)
	assert.Equal(t, nil, err)
	msgpack.Unmarshal(bytes, t2)
	fmt.Printf("%v", t2)
}

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in v3.2.4
