### ISSUE TITLE
Export Write/Read methods for Encoder/Decoder

### ISSUE THREAD

**Issue by n-canter** [vmihailenco/msgpack#170]
Can you export Write/Read methods?
Without these methods it is very difficult to use CustomEncoder/Decoder.
The only way to pass arbitrary slice of bytes is to implement Marshaller/Unmarshaller. But it's not what I want, when implement CustomEncoder/Decoder.

**Comment by vmihailenco** [comment]
Why not `enc.EncodeBytes(...)`? The overhead is minimal and you don't have to invent your own custom format.

**Comment by n-canter** [comment]
Using EncodeBytes() will change binary representation of the msgpacked struct. But we have clients which expect exact the same struct as have been passed to the encoder.

In my case I wanted to accelerate the Encoding part not affecting the Decoder.
The decoder is written in C++ and works pretty good. But the golang encoder works not very fast because of reflect magic.

**Comment by vmihailenco** [comment]
Again, why not:

```
e.EncodeMapLen(2) // struct has 2 fields

e.EncodeString("ID") // field name
e.EncodeInt(123) // field value

e.EncodeString("Username") // field name
e.EncodeString("vmihailenco") // field value
```

That should be reasonably fast.

**Comment by n-canter** [comment]
At first I found this approach not as fast, as I expected. But after you suggestion I investigated it a little bit deeper and it turned out that it was happening because I used ioutil.Discard in my benchmark as the output to the encoder.
ioutil.Discard was wrapped into byteWriter and WriteByte() calls were very expensive.

**Comment by vmihailenco** [comment]
Thanks for letting me know - byteWriter should be faster in master.
