### ISSUE TITLE
Array is end but readArrayEnd() is not called

### ISSUE THREAD

**Issue by ikenchina** [vmihailenco/msgpack#188]
hello, 
i encoded LoginU struct in Go and send to Java to decode,
but java's message pack library reported bellow errors

```
	Array is end but readArrayEnd() is not called
	org.msgpack.MessageTypeException: Array is end but readArrayEnd() is not called
	at org.msgpack.unpacker.UnpackerStack.checkCount(UnpackerStack.java:61)
```

// java code:
```
public class LoginPack {
	@Message
	public static class LoginU {
		public int version;
		public String ip; 
		public String openid;
		public String access_token;
		public String test_uid;
	}
}
```

// go code
```
type LoginU struct {
	version  int32
	ip       string
	openid   string
	token    string
	test_uid string
}

req := &LoginU{}
buf := bytes.NewBuffer([]byte{})
encoder := msgpack.NewEncoder(buf).StructAsArray(true)
encoder.Encode(req)


```

**Comment by vmihailenco** [comment]
There is no such thing as array end in msgpack. Superficially array is encoded as:
- array mark
- number of elements
- element1
- element2
- ...

Are you sure that msgpack Java supports `StructAsArray(true)` option?

**Comment by ikenchina** [comment]
if i didn't use StructAsArray(true) this option, msgpack java reported only supports array of struct
