### ISSUE TITLE
Make Encode/Decode similar to their json, xml and gob counterparts

### ISSUE THREAD

**Issue by prep** [vmihailenco/msgpack#189]
Currently, Encode looks like `Encode(v ...interface{}) error` and Decode looks like `Decode(v ...interface{}) error`, offering the ability to encode or decode more than a one thing in a single call.

This deviates from how packages like `encoding/json`, `encoding/xml` and `encoding/gob` do it. Of course, this is not a problem when using this package directly, but I find myself in a situation where I abstract away the encoder or decoder and it would be really nice if I could just pass one of the following interfaces:

```go
type Encoder interface {
	Encode(v interface{}) error
}

type Decoder interface {
	Decode(v interface{}) error
}
```

My current solution is to wrap msgpack's Encoder and Decoder as follows, but obviously I'd rather not have to do that:

```go
type msgpackDecoder struct {
	dec *msgpack.Decoder
}

func (dec *msgpackDecoder) Decode(v interface{}) error {
	return dec.dec.Decode(v)
}

type msgpackEncoder struct {
	enc *msgpack.Encoder
}

func (enc *msgpackEncoder) Encode(v interface{}) error {
	return enc.enc.Encode(v)
}
```

This is probably a long shot as it's a breaking change for implementers who call `Encode()` and `Decode()` with multiple parameters, but I wanted to bring it up anyway and hear your thoughts on this.

**Comment by vmihailenco** [comment]
Since this breaks API we can't do it without releasing new major version. So I would postpone this change until there are enough changes to make a new major release.
