### ISSUE TITLE
Make func (e *Encoder) write(b []byte) error - exported

### ISSUE THREAD

**Issue by WowVeryLogin** [vmihailenco/msgpack#190]
I would like to do encoding with other library (with code-generation for max performance), but I would like to use its result by vmihailenco/msgpack (in my case this library is used by go-tarantool). Currently it is not possible to plug already encoded message into Encoder. Can you please add some way to do it? One of the ways to do it fast is by making write method of encoder exported, so clients can mess up with underlying buffer on their own risk (I can make pull-request if it is acceptable solution). And same with Decoder to be able to obtain []byte slice and decode it by myself.

**Comment by vmihailenco** [comment]
I believe you should be able to do the following:

```go
buf := bytes.NewBuffer(data)
dec := msgpack.NewDecoder(buf)

// Read number of bytes
n, err := dec.DecodeInt()

// Use bytes.Buffer directly
b := make([]byte, n)
_, err := ioutil.ReadFull(buf, b)
```

The only caveat is documented in https://github.com/vmihailenco/msgpack/blob/master/decode.go#L55-L57.

Overall if you need max performance you can implement [custom encoder](https://godoc.org/github.com/vmihailenco/msgpack#example-CustomEncoder) manually or write code generator that will generate it for you.
