### ISSUE TITLE
Version 3.4 is API breaking

### ISSUE THREAD

**Issue by immesys** [vmihailenco/msgpack#199]
Commit d7937880410893738b447c32e66c0567c9a0379d changes the signature of the `Decode` function so that all software using this library fails to compile (if they had previously passed multiple arguments). I am not sure if this change should happen without a major version number increment.

Would it be possible to revert this change and instead release it under a new major version number? E.g v4. That way all the packages that import `gopkg.in/vmihailenco/msgpack.v3` or depend on v3.x via dependency management tools like dep will continue to work.

Thanks

**Comment by vmihailenco** [comment]
Done

**Comment by immesys** [comment]
Awesome! Thank you.

**Comment by immesys** [comment]
Tested and the problem is resolved. Both gopkg.in and dep are resolving the 3.3 tag as expected.
