### ISSUE TITLE
Struct value in map encoded and decoded as map

### ISSUE THREAD

**Issue by c4milo** [vmihailenco/msgpack#202]
I’m currently encoding a map[interface{}]interface{} with a struct value inside. I was hoping to decode the map, get the struct value and do a type assertion. However, the struct value is being decoded as a map[string]interface{}. Is this the expected behavior?

**Comment by vmihailenco** [comment]
Yes, that is expected behavior because by default msgpack does not record struct type and by Go does not allow to access arbitrary type by name. Instead you should register your type in `init` function as msgpack extension:

```go
package main

import (
	"fmt"

	"github.com/vmihailenco/msgpack"
)

type MyStruct struct {
	Id int
}

func init() {
	msgpack.RegisterExt(1, (*MyStruct)(nil))
}

func main() {
	in := map[string]interface{}{
		"foo": &MyStruct{Id: 123},
	}
	b, err := msgpack.Marshal(in)
	if err != nil {
		panic(err)
	}

	var out map[string]interface{}
	err = msgpack.Unmarshal(b, &out)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v", out)
}
```
