### ISSUE TITLE
Option to ignore some field during serialisation/deserialisation process

### ISSUE THREAD

**Issue by pavel-odintsov** [vmihailenco/msgpack#203]
Hello!

I have quite tricky case when I have quite big number of imported structures (from external library) and I need some way to encode and decode them from/to message pack.

But all structures imported from upstream library have one field (pointer to structure) which I must skip during encode/decode process.

Can you suggest best ways to implement it? I'm thinking about some custom marshaller/unmarshaller which can access list of ignored fields.

Thank you!

**Comment by tarnfeld** [comment]
This would be possible to do using a custom encoder and decoder, but the issue is that the struct we are decoding into is in another package. Defining a custom encoder outside of the package results in something like... ```cannot define new methods on non-local type```.

I noticed that you can use the `Register` function to register encoding and decoding functions for reflected types, so perhaps that is the right avenue.

**Comment by vmihailenco** [comment]
I guess the easiest way is to fork the library and add `if` statement [here](https://github.com/vmihailenco/msgpack/blob/master/encode_map.go#L151) that skips the field by name.  All other alternatives I see either require lots of work (like using `Register` function with custom encoder) or new API to somehow filter/omit the field.

**Comment by tarnfeld** [comment]
Yep, we ended up just using `Register` to do what we want. Using `Decoder.Skip()` worked fine.

**Comment by pavel-odintsov** [comment]
Yep, we solved issue this way:
```

func encodeRR_Header(enc *msgpack.Encoder, v reflect.Value) error {
	return enc.Encode("")
}

func decodeRR_Header(dec *msgpack.Decoder, v reflect.Value) error {
	return dec.Skip()
}

func init() {
	msgpack.Register(dns.RR_Header{}, encodeRR_Header, decodeRR_Header)
}
```
