### ISSUE TITLE
Returning to old encoding behavior for some types

### ISSUE THREAD

**Issue by gbl08ma** [vmihailenco/msgpack#211]
I have a project which is currently using v2 of this library. In trying to fix an unrelated problem, I realized that the latest version of this library is already v4, and decided to update to see if it fixed said unrelated problem (and also because it is generally good practice to keep dependencies up to date).

API-wise my code was fully compatible, however, clients (which use another library written in another language) were having trouble decoding objects encoded by the server. Closer inspection revealed this is because time.Time is now encoded in a different way than in v2 (clients are expecting time to come as an array of integers - a Java `long[]` - and they only care about the first element of the array, as that was the number of seconds since the epoch and offered enough precision). I believe eb7baa3b9ebe6515a47a6be829b973cf47ee602f was responsible for most of this change.

I have no doubt the new way of encoding time.Time is superior, but since updating the clients to support it is not feasible at this time, I wonder which is the best way to preserve the old behavior for this specific type while keeping the remaining improvements from the latest version? I looked into Register and RegisterExt but I am unsure how they will play with the fact that I'd be attempting to override an internal extension.

**Comment by vmihailenco** [comment]
>but I am unsure how they will play with the fact that I'd be attempting to override an internal extension

I am not sure too - the change you mentioned was long time ago. Please try and let me know if there are any problems.
