### ISSUE TITLE
Equivalent to json.RawMessage?

### ISSUE THREAD

**Issue by tisba** [vmihailenco/msgpack#217]
I'm trying to figure out how to achieve the following and I think something like json.RawMessage to delay decoding is what could be useful for this.

I have a very long stream of msgpack messages (100k+). Each message is a array with 2 elements. The first one is a small string "key". The second is the "payload", a large, nested map. I'd like have a efficient way to scan through all messages, to some matching on the first element and only in certain cases decode the second part for further processing. In case the second element is not needed, I would like skip decoding and simply "seek" to the next message.

I hope my description makes sense :) How would I build something like this using this package? With the json package I can use RawMessage to delay the decoding of the payload. But JSON is horribly inefficient for the payload I want to store.

**Comment by vmihailenco** [comment]
I would try something like this:

```
dec := msgpack.NewDecoder(...)

// decode number of messages
n, err := dec.DecodeArrayLen()

for i := 0; i < n; i++ {
    // decode number of fields
    elnum, err := dec.DecodeMapLen()
    // elnum == 2

    // decode small string key
    key, err := dec.DecodeString()

    if matches(key) {
        m, err := dec.DecodeMap() // decode large nested map
    } else {
        err := dec.Skip() // effeciently skip the map
    }
}
```

**Comment by tisba** [comment]
Thank you! VeryiInteresting. For your example to work, I have to have one large message pack with one very large array, right?

I'm not sure if this is a "standardise" thing, but I'm currently building "a stream" of messages using msgpack-ruby, see https://github.com/msgpack/msgpack-ruby#streaming-serialization. What they do for streaming, is to write message pack messages one after another. This is very nice, because I don't know in advance how many of those items in total we'll have; in my case one item is kind of a log entry or measurement.

But maybe that's the problem, because your package does not support streaming in this way, or I haven't understood how to do that...

**Comment by tisba** [comment]
Sorry, I was too quick with my reply.

I think I start to grasp how to decode a stream of message packs with your package.

Anyway, together with the hint that I should use `NewDecoder` over `Unmarshal` I think I can figure it out.

Thanks!
