### ISSUE TITLE
unknown multiple number of messages

### ISSUE THREAD

**Issue by tsaridas** [vmihailenco/msgpack#218]
I'm reading messages from a unix socket and for some reason it returns to the buffer an unknown amount of msgpack messages. When I unmarshal I only get the first one.

What I do in order to get the messages to a map[string]interface{} is 
Unmarshal the first one, marshall it again, convert it to string and get length.
Then I get the second message by removing the length of the first marshalled string from the stringed initial buffer and so on.

Is there a better way to do this ?

**Comment by vmihailenco** [comment]
>When I unmarshal I only get the first one.

Continue unmarshaling until the buffer is empty and you get EOF?

**Comment by tsaridas** [comment]
can you please show me an example of how do I continue unmarshaling the second messages and so on without doing all the things that I mentioned ?

**Comment by vmihailenco** [comment]
```
dec := msgpack.NewDecoder(bytes.NewBuffer(b))
dec.Decode(&msg1)
dec.Decode(&msg2)
```
