### ISSUE TITLE
 Invalid nil code while decode fixext type

### ISSUE THREAD

**Issue by cedricfung** [vmihailenco/msgpack#226]
For a custom type, I define the marshal and unmarshal method, the underlying data is []byte. The encoder produces data d400c0, but the decoder failed to decode it.

d4 means fixext1 type, 00 is the application custom type, c0 is the actual data payload.

But the decoder treat the payload c0 as nil.

**Comment by cedricfung** [comment]
This decoder produces correct output http://kawanet.github.io/msgpack-lite.

I think the decoder should not handle the c0 code for ext type, it should be left for the actual ext to handle it.

**Comment by vmihailenco** [comment]
Please provide a program that reproduces the problem.

**Comment by cedricfung** [comment]
```golang
package main

import (
	"encoding/hex"
	"fmt"
	"math/big"

	"github.com/vmihailenco/msgpack"
)

func init() {
	msgpack.RegisterExt(0, (*B)(nil))
}

type B struct {
	i big.Int
}

func (b B) MarshalMsgpack() ([]byte, error) {
	return b.i.Bytes(), nil
}

func (b *B) UnmarshalMsgpack(data []byte) error {
	b.i.SetBytes(data)
	return nil
}

func main() {
	b := B{*big.NewInt(192)}
	m, e := msgpack.Marshal(b)
	fmt.Println(hex.EncodeToString(m), e)

	var n B
	e = msgpack.Unmarshal(m, &n)
	fmt.Println(n.i.String(), e)
}
```

OUTPUT:

```
d400c0 <nil>
0 <nil>
```

**Comment by cedricfung** [comment]
@vmihailenco any comments about this issue?

**Comment by vmihailenco** [comment]
I understand the problem but the change you are proposing is
- backwards incompatible
- questionable overall since you want to embed some other encoding into msgpack stream

I would do something like

```
func (b B) EncodeMsgpack(enc *msgpack.Encoder) error {
    return enc.EncodeBytes(b.i.Bytes())
}

func (b *B) DecodeMsgpack(dec *msgpack.Decoder) error {
    data, err := dec.DecodeBytes()
    if err != nil {
        return err
    }
    b.i.SetBytes(data)
    return nil
}
```

It will be few bytes longer but overall safer and avoids the problem you reported.

Besides `big.Int` could be supported by this out of the box - https://github.com/vmihailenco/msgpack/issues/208

**Comment by cedricfung** [comment]
To discuss further, is this behavior normal according to the msgpack spec? Maybe some other library will encode the data as d400c0? Then this lib won't decode it, because just like http://kawanet.github.io/msgpack-lite it will decode the data correctly.
