### ISSUE TITLE
msgpack: invalid code=c4 decoding map length

### ISSUE THREAD

**Issue by shileislslsl** [vmihailenco/msgpack#231]
I use rpcx when this error happen,I want to know on what conditon this error will happen?
In my code,i use json to format go struct type to string as rpcx client argus.
```
func (s *Server) CallHall(method string, msghead string, v interface{}) ([]byte, error) {
	args := &public.ServerMsgReq{}
	if v == nil {
		v = "{}"
	}
	buf, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	args.Data = string(buf)
	args.Head = msghead
	buf, err = json.Marshal(args)
	if err != nil {
		return nil, err
	}

	resp := callRpc.CallHall(&public.Rpc_Args{MsgData: buf})
	return resp, nil
}
```
ERROR: rpcx: client protocol error:msgpack: invalid code=c4 decoding map length

any advise would be helpful!

**Comment by xkisu** [comment]
Did you solve this? I'm having the same problem

**Comment by DeryaKorkmaz** [comment]
I have the same problem
How can we solve ?

err = **msg="msgpack: invalid code=7b decoding map length"**

**Comment by 25b3nk** [comment]
Anybody solved this ? Please share the solution, thanks.
