### ISSUE TITLE
Does msgpack support extra field when unmarshal with customdecoder?

### ISSUE THREAD

**Issue by andyxning** [vmihailenco/msgpack#234]
In golang json unmarshal situation, we can have additional fields in struct when parsing JSON and those additional fields will be in empty value because there are no corresponding values in the json string.

But, in msgpack, if is use customdecoder like below:
```
dec.DecodeMulti(&m.ID, &m.Timestamp, &m.Attempts, &m.AbsTs, &m.AddedField)
```
and `m.AddedField` is a new additional field. An EOF error will be returned.

Although, i can use 
```
if err := dec.DecodeMulti(&m.ID, &m.Timestamp, &m.Attempts, &m.AbsTs, &m.AddedField); err != io.EOF {
		return err
	}
```
to workaround this with other fields successfully initialized with `m.AddedField` in empty value. But i am somewhat in doubt and want to confirm whether the way i used above is the canonical way.

**Comment by vmihailenco** [comment]
I am in doubt too. Unless you are programming for some restricted environment with limited amount of memory - don't bother saving few bytes. None will notice it but bugs will be nasty. Just use struct or slice if you feel adventurous.

But If you really need it:

```go
// Required fields.
if err := dec.DecodeMulti(&m.ID, &m.Timestamp, &m.Attempts, &m.AbsTs); err != nil {
    return err
}

// Optional.
if err := dec.Decode(&m.AddedField); err != nil && err != io.EOF {
    return err
}
```

You can also check number of bytes left in the `bytes.Buffer`.

**Comment by andyxning** [comment]
> Just use struct or slice if you feel adventurous.

@vmihailenco Thanks for the response. But could you please give an example of what you said? I can not understand it clearly.

> You can also check number of bytes left in the bytes.Buffer

What does this mean? :)

**Comment by vmihailenco** [comment]
>But could you please give an example of what you said?

Encode and decode the whole struct `msgpack.Marshal(m)`, not the individual fields.

>You can also check number of bytes left in the bytes.Buffer

You have bytes buffer with the date from which you are decoding. Use https://golang.org/pkg/bytes/#Buffer.Len to check how many bytes do you have there left.

**Comment by andyxning** [comment]
@vmihailenco Thanks for your detailed answers!
