### ISSUE TITLE
Why use github.com/vmihailenco/msgpack/v4/codes?

### ISSUE THREAD

**Issue by bestkillua** [vmihailenco/msgpack#237]
Hi, I can't found github.com/vmihailenco/msgpack/v4/codes, but decode.go has github.com/vmihailenco/msgpack/v4/codes, why? It occurs "cannot find package "github.com/vmihailenco/msgpack/v4/codes" in any of" when compile

**Comment by vmihailenco** [comment]
You need go with [Modules](https://github.com/golang/go/wiki/Modules) support and use semantic version importing - `import "github.com/vmihailenco/msgpack/v4"`

**Comment by wencan** [comment]
My team use Go 1.10.
My go package manager tool is govendor.
How to solve this problem?

**Comment by dabpop139** [comment]
Copy https://github.com/vmihailenco/msgpack/blob/master/codes/codes.go To local github.com/vmihailenco/msgpack/v4/codes
