### ISSUE TITLE
Autoinline embed pointer issue

### ISSUE THREAD

**Issue by stdiopt** [vmihailenco/msgpack#240]
Problem:

https://play.golang.org/p/XyJla4AhznG

Basically encoding uses [this](https://github.com/vmihailenco/msgpack/blob/master/types.go#L269-L284) to solve embed fields, and since the main encoded value is not a pointer the indirectNew returns on !v.CanSet().

and even if it is a pointer it would be better to not instantiate values on the encoded struct :thinking:

**Comment by vmihailenco** [comment]
I've fixed the crash, but let's not close this since it is an interesting corner case which we may want to tackle later. Note that you need to use v4

```
go mod init github.com/my/repo
go get github.com/vmihailenco/msgpack/v4
```
