### ISSUE TITLE
how can I use version v4 if my project doesn't use the go module instead of gopath

### ISSUE THREAD

**Issue by yingyan003** [vmihailenco/msgpack#251]
Hi, team, currently, my project does't use go module instead of gopath, if go use "go get -u github.com/vmihailenco/msgpack/v4" to pull the codes,  I got an error 
```
package github.com/vmihailenco/msgpack/v4: cannot find package "github.com/vmihailenco/msgpack/v4" in any of:
        /usr/local/go/src/github.com/vmihailenco/msgpack/v4 (from $GOROOT)
        /Users//goprojects/src/github.com/vmihailenco/msgpack/v4 (from $GOPATH)
```
Can I pull the version v4 under gopath, if no, how can I pull the newest codes? thanks

**Comment by vmihailenco** [comment]
This question is not specific to this lib - use whatever works in Go.
