### ISSUE TITLE
BinaryMarshaler cannot be decoded correctly from older versions

### ISSUE THREAD

**Issue by jameshartig** [vmihailenco/msgpack#255]
We have the following type which used to encode as a map since it was a struct, but since it implements the `BinaryMarshaler` (because it embeds `time.Time`) interface it cannot decode any old msgpack encodings. It looks like the marshaler support was added in #243.

```
type TS struct {
	time.Time
}
```

Here's a byte sequence from the old version:
```
[]byte{0x81, 0xa4, 0x54, 0x69, 0x6d, 0x65, 0xd6, 0xff, 0x5e, 0x17, 0x99, 0xc1}
```

How should this be handled going forward? We are currently blocked from upgrading until this is resolved. I was considering adding the following:
```

// MarshalMsgpack implements the msgpack.Marshaler interface
// TODO: remove this once we're done with backwards compatibility
func (t TS) MarshalMsgpack() ([]byte, error) {
	// for now keep marshalling it as a struct for backwards compatibility
	// we can't embed time.Time since it also implements BinaryMarshaler
	return msgpack.Marshal(struct {
		Time time.Time
	}{Time: t.Time})
}

// UnmarshalMsgpack implements the msgpack.Unmarshaler interface
func (t *TS) UnmarshalMsgpack(b []byte) error {
	// treat the TS as bytes since the encoder probably used MarshalText
	var tsb []byte
	err := msgpack.Unmarshal(b, &tsb)
	if err == nil {
		return t.UnmarshalBinary(tsb)
	}
	// try unmarshalling into a struct since newer msgpack added support for
	// using binary encoding interface (https://github.com/vmihailenco/msgpack/pull/243)
	// we can't embed time.Time since it also implements BinaryMarshaler
	var ta struct {
		Time time.Time
	}
	err2 := msgpack.Unmarshal(b, &ta)
	if err2 != nil {
		// return the original error since we tried the struct and it didn't work
		return err
	}
	t.Time = ta.Time
	return nil
}
```
Is there a better solution?

**Comment by vmihailenco** [comment]
I don't know a better way except that I would use `msgpack.CustomEncoder` (it is more flexible when working with msgpack) and simplify code a bit:

```
type rawTS TS // drop all methods

func (t TS) EncodeMsgpack(enc *msgpack.Encoder) error {
	// for now keep marshalling it as a struct for backwards compatibility
	// we can't embed time.Time since it also implements BinaryMarshaler
	return enc.Encode((rawTS)(ts))
}
```

This version does not allocate and should be as fast as it used to be.

**Comment by fastest963** [comment]
Unfortunately that won't work because `time.Time` implements the `BinaryMarshaler` interface and so even `rawTS` will still implement it since `TS` embeds `time.Time`. That's why I had to do `struct {Time time.Time}{Time: t.Time}`.

Is this something that the decoder can check for internally? If the code indicates it's a map type then don't try to do the binary unmarshalling even if it implements the `BinaryUnmarshaler` interface because it might've been encoded by an older version of the library.

**Comment by vmihailenco** [comment]
You can try

```go
type rawTS TS

func (rawTS) MarshalBinary() {}
```

>it might've been encoded by an older version of the library

It is complicated and it does not fix the problem in long term.
