### ISSUE TITLE
decoder should supports bytes.Buffer{} 

### ISSUE THREAD

**Issue by iwind** [vmihailenco/msgpack#259]
Sometimes, we will write bytes to decoder in some pieces, but msgpack will not work well under this condition.

Here is a example to show the problem:
~~~go
func TestOriginBuffer(t *testing.T) {
	data, err := msgpack.Marshal("Hello, World")
	if err != nil {
		t.Fatal(err)
	}

	buffer := bytes.NewBuffer(data[:5]) // put first 5 bytes
	decoder := msgpack.NewDecoder(buffer)
	var value interface{}
	err = decoder.Decode(&value)
	if err != nil {
		// we know there will be EOF error as expected
		// I thought if buffer has reached EOF, it will wait for next input
	}

	buffer.Write(data[5:]) // put left bytes
	err = decoder.Decode(&value) // decode again
	if err != nil {
		t.Fatal(err)
	}
	t.Log(value) // we expected "Hello, World" but "111" returned
}
~~~

I suggests if decoder reach a EOF, it should keep the unfinished object bytes, and join with next input bytes for decoding.

**Comment by vmihailenco** [comment]
This lib does not wait on more input when EOF is reached, because EOF means that there will not be more input. You should change your design.

**Comment by iwind** [comment]
> This lib does not wait on more input when EOF is reached, because EOF means that there will not be more input. You should change your design.

Thank you for quick reply, i already write a custom Buffer to handle it.
