### ISSUE TITLE
can't encode []StringAlias

### ISSUE THREAD

**Issue by jwfang** [vmihailenco/msgpack#27]
define StringAlias as follow:
type StringAlias string

then encode []StringAlias will panic.

test code:

package main

import (
        msgpack "gopkg.in/vmihailenco/msgpack.v2"
)

type StringAlias string

func main() {
        msgpack.Marshal([]StringAlias{StringAlias("sa")})
}

**Comment by vmihailenco** [comment]
Fixed, thanks for the report.
