### ISSUE TITLE
Documentation for tags

### ISSUE THREAD

**Issue by gdamore** [vmihailenco/msgpack#273]
Exploring the code I uncovered some interesting tags, including support for interning strings, etc.

It would be good to document what they are all, assuming that the intention is that they actually be supported for application use.

(At the moment I'm looking to see how to exclude a field from being omitted when the structure is marshalled.)

**Comment by vmihailenco** [comment]
I've added initial version at https://msgpack.uptrace.dev/#struct-tags. String interning is still beta and will be documented later.
