### ISSUE TITLE
Compatibility between 2.1.2 & 2.1.3

### ISSUE THREAD

**Issue by Dal-Papa** [vmihailenco/msgpack#28]
Hello !

We've been using your library for internal development and we're very happy about it.

The other day, one of the guy updated his server to 2.1.3 and it started to break many services that were interacting with it as they were trying to decode some MsgPack 2.1.2 and were getting some 2.1.3 encoded. 

As it's Embedded structure, we thought it might be due to one of your last commits and reverted back to 2.1.2 all the servers. 

Was it intentional or did you not know there was compatibility issues between both ?

Thanks.

**Comment by vmihailenco** [comment]
Hi,

v2.1.3 fixed https://github.com/vmihailenco/msgpack/issues/20. Basically what happened was
- v2.x broke v1 behaviour (unintentionally)
- v2.1.3 broke v2.x behaviour to restore v1 behaviour

I hoped none will notice :/

The only suggestion I have is to release v2.1.4 that will be able to decode bytes produced by v2.1.2. But v2.1.2 will not be able to decode bytes produced by v2.1.4. So you still have to upgrade all servers at once. Sorry.

**Comment by Dal-Papa** [comment]
Just so you know, you can't update from 2.2.1 to 2.3 : 
```
~/go/src/gopkg.in/vmihailenco/msgpack.v2$ git log
commit 9f5408dd4233be7d326caf19017c8efcddc9372b

~/go/src/gopkg.in/vmihailenco/msgpack.v2$ git pull 
Auto-merging types_test.go
CONFLICT (content): Merge conflict in types_test.go
Auto-merging typeinfo.go
CONFLICT (content): Merge conflict in typeinfo.go
Automatic merge failed; fix conflicts and then commit the result.
```

Did you hope no one would notice here neither :stuck_out_tongue: ?

**Comment by vmihailenco** [comment]
I have no idea how git pull can cause merge conflict. Any hints?

Also you should use `go get -u gopkg.in/vmihailenco/msgpack.v2` to update the lib.

**Comment by Dal-Papa** [comment]
Maybe you discontinued your branch. When I look at your Graph Tree it seems like it : 
<img width="466" alt="screen shot 2015-07-30 at 14 35 00" src="https://cloud.githubusercontent.com/assets/1805746/8995753/50320a9c-36c8-11e5-91b6-6bbe1f667510.png">
And we did use `go get -u -f` at first and that's what showed us there was a problem with your dependency. A simple `rm` of the repo and `go get` again did the trick. Just wanted to let you know :wink:

**Comment by vmihailenco** [comment]
Thanks, I guess I have to start creating branches when I release new major version.
