### ISSUE TITLE
Unmarshaling []interface{map[int]string} fails

### ISSUE THREAD

**Issue by philippseith** [vmihailenco/msgpack#290]
```golang
v := []interface{}{map[int]string{1: "1"}}
b, _ := msgpack.Marshal(v)
var v2 []interface{}
fmt.Printf("%v", msgpack.Unmarshal(b, &v2))
```

prints msgpack: invalid code=1 decoding string/bytes length

## Expected Behavior

Unmarshal should unmarshal correctly and return nil

## Current Behavior

Unmarshal returns an error. If the map is not wrapped in an array, unmarshaling works. If the `[]interface{}` contains other non-map types instead, unmarshaling works.

## Possible Solution

In `decodeInterface()` at https://github.com/vmihailenco/msgpack/blob/f99999d3a42fb622bb3db18b4d1a260fe920a07f/decode.go#L389 `decodeMapDefault()` is called, which calls `DecodeMap()`, which is only able to decode to map[string]interface{}. 

`decodeMapDefault()` or the line above  should call `DecodeTypedMap()` instead.

## Steps to Reproduce

playground: https://play.golang.org/p/GzQ6ss8n5AL

## Context (Environment)

I am writing a SignalR server in go (see https://github.com/philippseith/signalr). I want to deserialise an array with arbitrary elements as parameters for a SignalR method invocation: https://github.com/philippseith/signalr/blob/7328cb4a0aef77accc9833abc99f63d0b21ba2e5/messagepackhubprotocol.go#L71. At this layer in the server code is no information about the parameter types of the called method available.

**Comment by vmihailenco** [comment]
Did you see https://msgpack.uptrace.dev/#decoding-maps-into-an-interface?

**Comment by philippseith** [comment]
Yes, I saw that. SignalR RPC messages are encoded as Arrays in MessagePack with some simple, fixed typed elements but one element which itself is a slice of arbitrary complex elements (the method parameters of the method invoked by that SignalR message). 
It would be very simple to decode the message with `DecodeSlice()`, if this method wouldn't assume that every map that it finds in the contained object tree is of type map[string]interface{}

**Comment by vmihailenco** [comment]
Sounds like you want

```go
dec := msgpack.NewDecoder(&buf)
dec.SetMapDecoder(func(dec *msgpack.Decoder) (interface{}, error) {
    return dec.DecodeTypedMap()
})
```

**Comment by philippseith** [comment]
I tried that, but it failed differently.  A SignalR message slice always contains a map as second element, which is empty in most cases. Turns out, DecodeTypedMap does not work on empty maps. 
But returning `dec.DecodeUntypedMap()` works with that empty map and fulfils my other requirements (so far :-))

**Comment by vmihailenco** [comment]
@philippseith I've updated `DecodeTypedMap` to return nil map when map is empty.
