### ISSUE TITLE
Encoder generating corrupted data

### ISSUE THREAD

**Issue by rafaeljusto** [vmihailenco/msgpack#295]
When encoding a structure that contains a pointer to `time.Time` the generated bytes are corrupted and cannot be decoded.

## Expected Behavior

The library should decode any encoded value.

## Current Behavior

Library fails to decode an encoded value generated by itself.

## Possible Solution

Looks like the issue started happening after [this commit](https://github.com/vmihailenco/msgpack/pull/254/commits/52c51806fbc04fc32af34ec204d12e49f43e20e0). Maybe we need to handle `*time.Time` or create a special case.

## Steps to Reproduce

Test:
```go
func TestIssue(t *testing.T) {
	type example struct {
		TimePtr *time.Time
	}

	v1 := example{
		TimePtr: func() *time.Time {
			v := time.Date(2021, 1, 28, 0, 0, 0, 0, time.UTC)
			return &v
		}(),
	}

	var buf bytes.Buffer
	encoder := msgpack.NewEncoder(&buf).UseCompactEncoding(true)

	if err := encoder.Encode(v1); err != nil {
		t.Fatal(err)
	}

	var v2 example
	if err := msgpack.Unmarshal(buf.Bytes(), &v2); err != nil {
		t.Fatal(err)
	}
}
```

Output:
```shell
$ go test
OK: 16 passed
--- FAIL: TestIssue (0.00s)
    types_test.go:1116: msgpack: invalid code=d6 decoding bytes length
FAIL
exit status 1
FAIL	github.com/vmihailenco/msgpack/v4	0.707s
```

## Context (Environment)

Started happening on `v4.3.9` and also happening on the latest version of `v4`.

**Comment by rafaeljusto** [comment]
If I remove [this condition](https://github.com/vmihailenco/msgpack/blob/52c51806fbc04fc32af34ec204d12e49f43e20e0/encode_value.go#L54-L58) the test works. 🤔  Comparing the encoded bytes we get some differences below.

#### With the condition
```
81 a7 54 69 6d 65 50 74 72 d6 ff 60 11 fe 80
```
Appears to be [timestamp 32](https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type) (d6).

#### Without the condition
```
81 a7 54 69 6d 65 50 74 72 c4 0f 01 00 00 00 0e d7 a3 f5 80 00 00 00 00 ff ff
```

Appears to be [timestamp 64](https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type) (d7). There's also some extra information before the date (`c4 0f 01 00 00 00 0e`).

**EDIT:** Without the condition it doesn't call the `encodeTime` at all, so it's probably encoding as something else. Sorry, trying to learn the library via reverse engineering.

**Comment by vmihailenco** [comment]
This seems to be working in v5 so I would try to upgrade to v5. Old versions don't receive updates...

**Comment by rafaeljusto** [comment]
Yeah, test pass on v5. Going to close this one. Thanks!

**Comment by rafaeljusto** [comment]
@vmihailenco Is there any backward incompatibility from v4 to v5? Regarding data encoded in v4 and decoded by v5 I mean. It's not clear from the Changelog. I'm just thinking about how would be the migration here. 🙂

**Comment by vmihailenco** [comment]
v5 should be able to decode all data encoded with v4.
