### ISSUE TITLE
Allow `:` to be used in struct-labels

### ISSUE THREAD

**Issue by mthjs** [vmihailenco/msgpack#296]
Currently the tag-parser sees every tag with a `:` as a key-value-pair. Some software I've to deal with uses `:` also as the labels/names. This doesn't seem to be an issue for maps.

## How To Reproduce

```
package main

import (
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
)

type Message struct {
	Device string   `msgpack:"device:uid"`
	Payloady string `msgpack:"payload"`
}

func main() {
	og := map[string]string{
		"device:uid": "it-be-me",
		"payload": "this is what I have to say",
	}
	packed, err := msgpack.Marshal(og)
	if err != nil { panic(err) }
	var msg Message
	if err := msgpack.Unmarshal(packed, &msg); err != nil { panic (err) }
	fmt.Printf("%#v\n", msg)
	var mapped map[string]string
	if err := msgpack.Unmarshal(packed, &mapped); err != nil { panic (err) }
	fmt.Printf("%#v\n", mapped)
}
```

### Presumed Output

```
main.Message{Device:"it-be-me", Payloady:"this is what I have to say"}
map[string]string{"device:uid":"it-be-me", "payload":"this is what I have to say"}
```

### Actual Output

```
main.Message{Device:"", Payloady:"this is what I have to say"}
map[string]string{"device:uid":"it-be-me", "payload":"this is what I have to say"}
```

## Possible Solution

There are two ways to solve this, on is to allow to escape `:` in tag-names, the other is presume the first value within the `msgpack` tag's quotes to be the name/label meaning `:` holds no special meaning and will just be seen as any other character.

## Possible Implementation

There is already a pull-request for the tag-parser https://github.com/vmihailenco/tagparser/pull/3 which allows `:` to be escaped

I've also taken the liberty to add a double-quoted case which does the same as the aforementioned pull-request, but instead of prepending `:` with two '\' we can just wrap the value into double-quotes. https://github.com/vmihailenco/tagparser/pull/4

**Comment by vmihailenco** [comment]
`msgpack:"'device:uid'"` should already work. Let's continue this discussion in tagparser repo.
