### ISSUE TITLE
Panic on embedded pointer struct

### ISSUE THREAD

**Issue by jhwz** [vmihailenco/msgpack#298]
Issue tracker is used for reporting bugs and discussing new features. Please use
[Discord](https://discord.gg/rWtp5Aj) or [stackoverflow](https://stackoverflow.com) for supporting
issues.

## Expected Behavior

Marshaling and unmarshaling work as expected

## Current Behavior

When calling msgpack.Unmarshal get `panic: reflect: call of reflect.Value.IsNil on struct Value` when the struct has an embedded field with custom unmarshaling

## Steps to Reproduce

```go

type E struct {
	val int
}

func (e *E) UnmarshalMsgpack(data []byte) error { return nil }

func TestMsgpack(t *testing.T) {

	type P struct {
		*E
	}

	before := &P{E: &E{10}}

	data, _ := msgpack.Marshal(before)

	after := &P{}
	msgpack.Unmarshal(data, after)
}
```

## Detailed Description

Works fine if the embedded field is a value and not a pointer. Tricky when you want nullable fields though!

## Possible Implementation

Not sure haven't looked at source much

**Comment by vmihailenco** [comment]
Please provide full program.

**Comment by jhwz** [comment]
If you copy and paste the example above, the issue is fully reproduced. Not sure what more you need.

**Comment by vmihailenco** [comment]
@jhwz

**Comment by vmihailenco** [comment]
@jhwz indeed, sorry. https://github.com/vmihailenco/msgpack/pull/300 (v5.2.2) fixes the panic, but you still need to do something like this to make this working

```go
type P struct {
    *E
}

func (p *P) UnmarshalMsgpack(data []byte) error { 
    if p.E == nil { p.E = new(E) }
    return p.E.UnmarshalMsgpack(data)
}
```

The problem is that msgpack calls `p.UnmarshalMsgpack` which in turn calls `p.E.UnmarshalMsgpack` but `p.E` is `nil`. I don't think there is an easy way around this problem.
