### ISSUE TITLE
Using omitempty with a value that implements interface{IsZero() bool} does not check if the value is nil

### ISSUE THREAD

**Issue by alfrunes** [vmihailenco/msgpack#302]
## Expected Behavior

If a struct field is "omitempty" and nil, but implements `interface{ IsZero() }`, the condition that the value is nil should take precedence.

## Current Behavior

The following example will panic from a nil-pointer exception:
```go
s := struct{
  T *time.Time `msgpack:",omitempty"`
}{}
msgpack.Marshal(s)
```
## Possible Solution

[isEmptyValue](https://github.com/vmihailenco/msgpack/commit/2d5c939191118a5caa1d38070b6d13b79cbb09f6#diff-b990161986c40e0867e71c60779bc98a8730a9eb0ca5866ae8189e126863c059R320) should check if the interface is nil before calling IsZero.

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/vmihailenco/msgpack/commit/e1f7a34054d0765b4b8329163736f06625e3b029

**Comment by alfrunes** [comment]
Thank you!
