### ISSUE TITLE
Encode integers without code prefix

### ISSUE THREAD

**Issue by asdine** [vmihailenco/msgpack#303]
## Expected Behavior

When using custom ext codes, we would like to write our ext code using `EncodeExtHeader` then call functions like `EncodeInt` without them writing their own code.
It would be very handy to export some methods to be able to control granularly how they are encoded.

The goal is to have something like this:

```
| custom ext code |  encoded integer value |
```

## Current Behavior

```
| custom ext code | integer code | encoded integer |
```

## Possible Solution

Exporting / adding some lower level primitives:

```go

// WriteCode writes a code to the writer.
// It can be used to manually encode a value to the writer.
func (e *Encoder) WriteCode(code int8) error

// WriteInteger encodes an int64 in 1, 2, 4 or 8 bytes and writes it to the writer.
// This method can only be called after having called WriteCode.
func (e *Encoder) WriteInteger(i int64) error
```

## Context (Environment)

In GenjiDB, we are trying to encode some values alongside SQL type information.
So far, our type system maps very well with MessagePack types (`INTEGER` as int, `DOUBLE` as float, etc.), this allows us to no have to encode any additional metadata, and decode without any schema.
However, we would like the `DOUBLE` type (which is an 8 bytes float) to take as little space as possible.  For that we want to encode it as an integer when it can be converted to an integer without loss, and encode it as float otherwise.
`UseCompactFloats` doesn't work for us because it doesn't keep original type information (the float is encoded as an int, with the int code), as when decoding we want to know precisely what SQL type it was in the first place.
To achieve this trick, we want to use a custom ext type that indicates that this value is a double that has been encoded as an integer.

**Comment by vmihailenco** [comment]
If we add `WriteInt` then we also need to add `WriteUint`. Then `WriteFloat`. And explain the difference between `WriteInt` and `EncodeInt`. Even then some people will misuse such confusing API.

I think the API for this should resemble `encoding.Binary`

```go
msgpack.PutUint64([]byte, uint64) int
```

So it can be used like this:

```go
b := make([]byte, 8)
n := msgpack.PutUint64(b, num)

w := enc.Writer()
w.WriteByte(code)
w.Write(b[:n])
```

What do you think?

**Comment by asdine** [comment]
That looks much better indeed

**Comment by asdine** [comment]
I'd be happy to submit a PR this weekend if you want

**Comment by vmihailenco** [comment]
@asdine sounds good :+1:

**Comment by asdine** [comment]
After investigation, I don't think this change has anything to do with this library or MessagePack in general. The MessagePack spec provides an API to deal with this and writing the right adapters is really easy with this library.

It turns out it is doable really easily with a custom ext code and these two functions:

```go
// putUint encodes an uint64 in 1, 2, 4, or 8 bytes.
// Type of the number is lost during encoding.
func putUint(b []byte, n uint64) int {
	if n <= math.MaxUint8 {
		b[0] = uint8(n)
		return 1
	}
	if n <= math.MaxUint16 {
		binary.BigEndian.PutUint16(b, uint16(n))
		return 2
	}
	if n <= math.MaxUint32 {
		binary.BigEndian.PutUint32(b, uint32(n))
		return 4
	}

	binary.BigEndian.PutUint64(b, n)
	return 8
}

// readUint decodes an uint encoded in 1, 2, 4 or 8 bytes.
func readUint(b []byte, n int) uint64 {
	switch n {
	case 1:
		return uint64(b[0])
	case 2:
		return uint64(binary.BigEndian.Uint16(b))
	case 4:
		return uint64(binary.BigEndian.Uint32(b))
	case 8:
		return uint64(binary.BigEndian.Uint64(b))
	}

	panic(fmt.Sprintf("unexpected uint size %d", n))
}
```

Here is the encoding part:
```go

const compactFloatExtCode = 0x1

func (e *encoder) encodeCompactFloat(f float64) error {
	if float64(int64(f)) != f {
		return e.enc.EncodeFloat64(f)
	}

	b := make([]byte, 8)
	// convert the float to a signed int then
	// convert it to an uint
	n := putUint(b, uint64(int64(f)))

	err := e.enc.EncodeExtHeader(compactFloatExtCode , n)
	if err != nil {
		return err
	}

	w := e.enc.Writer()
	_, err = w.Write(b[:n])
	return err
}
```

Here is a full implementation if needed https://github.com/genjidb/genji/commit/e4aecc5dc8bee2ae29f6f9111598cc94dc2d1a19

I'm closing this issue as I don't think this should be integrated into this library, but I might be wrong so feel free to reopen if you think otherwise.
