### ISSUE TITLE
decode empty array got an error "msgpack: number of fields in array-encoded struct has changed"

### ISSUE THREAD

**Issue by vosey** [vmihailenco/msgpack#308]
when I pack an empty array in php, just like this: $packed_empty_arr = msgpack_pack([]), then use this library to unpack it in go, I've got an error: "msgpack: number of fields in array-encoded struct has changed"，

Example code：

```
type ss struct {
}  // used instead of the empty array in php way

type sss struct {
	A struct {
            Aa string
        }
        B string
}

buf := new(bytes.Buffer)

enc := msgpack.NewEncoder(buf)
enc.Encode([]ss{})

dec := msgpack.NewDecoder(buf)

var s1 sss
err := dec.Decode(&s1)

if err != nil {
    panic(err) // msgpack: number of fields in array-encoded struct has changed
}
```

The empty array is considered as optional, so I want to decode it correctly, no matter it is empty or not. I don’t know if this is a bug.  Can you give me some suggestions? Or as a bug fix?   @vmihailenco

**Comment by vmihailenco** [comment]
The handling of an empty array should be fixed in v5.3.3
