### ISSUE TITLE
Doc: UseJSONTag() removal should be documented in the changelog.

### ISSUE THREAD

**Issue by methane** [vmihailenco/msgpack#312]
https://github.com/vmihailenco/msgpack-docs/ is 404 so I am filing this issue here.

See v5 changelog. https://msgpack.uptrace.dev/changelog/#v5
Please add this:

Removed: `UseJSONTag(bool)` is removed. Use `SetCustomStructTag("json")` instead.

**Comment by vmihailenco** [comment]
Added to https://github.com/vmihailenco/msgpack/blob/v5/CHANGELOG.md#removed. Thanks.
