### ISSUE TITLE
Upgrade to version 5.1 is breaking the unMarshal for map of string and interface

### ISSUE THREAD

**Issue by yugandharbandi2220** [vmihailenco/msgpack#315]
After upgrading from 5.0.0 beta to 5.1, observed that unMarshal is producing unexpected behavior for map[string]interface{}

## Expected Behavior

In previous versions, the unMarshal of time as value inside map[string]interface{} used to return pointer to time

## Current Behavior

In the current version it is returning the value instead of reference

## Possible Solution

After going through the code, I can see that https://github.com/vmihailenco/msgpack/blob/v5/ext.go#L266 this line changed the behavior

## Steps to Reproduce

Sample Snippet to reproduce
   ``` go
    values := make(map[string]interface{})
    tmp := time.Now()
    values["time"]= &tmp
    bytes, _ := msgpack.Marshal(values)
    values = make(map[string]interface{})
    err := msgpack.Unmarshal(bytes, &values)
```
Wanted to know if this is done intentional

**Comment by vmihailenco** [comment]
I believe it was intentional after reworking / cleaning up how msgpack extensions are decoded. I honestly don't remember the exact  details (most likely it just came out naturally), but anyway msgpack v5 is out for some time now and it is too late to change the current bevavior...

**Comment by yugandharbandi2220** [comment]
Got it. Thanks
