### ISSUE TITLE
Decoding doesn't recognise nested Unmarshaler interfaces

### ISSUE THREAD

**Issue by dim** [vmihailenco/msgpack#32]
To demonstrate the issue, I have updated the test from #30 in https://github.com/dim/msgpack/blob/bug/marshal-interfaces/custom_test.go, by rewriting the `msgpack.Register` callbacks as `MarshalMsgpack`/`UnmarshalMsgpack`, implementing both, the `Marshaler` and the `Unmarshaler` interface. 

The test is now failing - it looks like nested structs are not recognised correctly as `Unmarshaler` interfaces.

**Comment by vmihailenco** [comment]
The issue is that `UnmarshalMsgpack` takes `[]byte` as an argument and therefore we can't tell how much bytes were read. Probably `UnmarshalMsgpack` should take `*Decoder` as an argument. Need to think about it.

**Comment by vmihailenco** [comment]
Should be fixed by new interface in https://github.com/vmihailenco/msgpack/pull/33
