### ISSUE TITLE
Overflow when converting `timeExtID` to `byte`

### ISSUE THREAD

**Issue by tehsphinx** [vmihailenco/msgpack#323]
Don't have a description what can fail because of this, but it doesn't look like this should be:

```go
if err := e.w.WriteByte(byte(timeExtID)); err != nil {
```

`timeExtID` is declared as int8 = -1, which does not fit into `byte`.

This can be found in file `time.go`.

**Comment by vmihailenco** [comment]
It is okay to send int8 as uint8 and vice versa. The value is preserved.

**Comment by tehsphinx** [comment]
Not exactly sure what you mean.

I'm quite sure, this is sending `255` instead of `-1`, unless that is what you want.
https://play.golang.org/p/bw6LiCs1_KM

**Comment by vmihailenco** [comment]
`int8(-1)` has the same byte representation as `uint8(255)`. Later you can decode `byte` as `int8` or `uint8` to get signed or unsigned number.

**Comment by tehsphinx** [comment]
ok, got it.
