### ISSUE TITLE
Encode struct in struct ，but decode the embedded Struct to map

### ISSUE THREAD

**Issue by lychjck** [vmihailenco/msgpack#325]
Encode： {Term:1 LeaderID:2503345136 PrevLogIndex:-1 PrevLogTerm:-1 LeaderCommit:0 Entries:[{Command:{Name:cam_color_server Inst:2320539470} Term:1}]}
Decode： {Term:1 LeaderID:2503345136 PrevLogIndex:-1 PrevLogTerm:-1 LeaderCommit:0 Entries:[{Command:map[Inst:2320539470 Name:cam_color_server] Term:1}]}

**Comment by vmihailenco** [comment]
This requires more details.
