### ISSUE TITLE
Can performance be improved for deserializing only subset of fields

### ISSUE THREAD

**Issue by prashanthellina** [vmihailenco/msgpack#55]
I use msgpack serialization for storing about 10 billion records. Each record has around 15 fields in a go struct. The most common use case is that of reading from this set and examining some fields to do processing. In the whole process, I realized that most of the time is being spent in msgpack deserialization to map[string]interface{}.

I noticed that I usually only read a small subset of the fields. Is there a way to improve deserialization performance by only reading those fields I need? (I tried defining a struct with only those fields but that made performance worse than using a map[string]interface{}).

Something along the lines of the following might be useful.

```go
type SubData struct {
	Y string
}

type Record struct {
	A int
	B SubData
	C int
	D string
	E []int
	F bool
}

A := msgpack.DeserializeInt(record_bytes, "A")
B := msgpack.DeserializeString(record_bytes, "B.Y")
```

or

```go
type DeserializedSubData struct {
	Y string
}

type DeserializedRecord struct {
	A int
	B DeserializedSubData
}

var d DeserializedRecord
msgpack.Deserialize(record_bytes, &d)
```

Please note that the second case works currently but performance isn't any better for reading only some fields.

**Comment by vmihailenco** [comment]
https://github.com/vmihailenco/msgpack/pull/56 should improve performance a bit.

You can get a significant performance boost if you the order of your fields, e.g. with custom encoder/decoder:

```
package main

import (
	"bytes"
	"fmt"

	"gopkg.in/vmihailenco/msgpack.v2"
)

type MyStruct struct {
	Name  string
	Age   int
	Color string
}

var (
	_ msgpack.CustomEncoder = &MyStruct{}
	_ msgpack.CustomDecoder = &MyStruct{}
)

func (s *MyStruct) EncodeMsgpack(enc *msgpack.Encoder) error {
	return enc.Encode(
		s.Name,
		s.Age,
		s.Color,
	)
}

func (s *MyStruct) DecodeMsgpack(dec *msgpack.Decoder) error {
	return dec.Decode(
		&s.Name,
		&s.Age,
		&s.Color,
	)
}

func main() {
	s := MyStruct{
		Name:  "Bob",
		Age:   12,
		Color: "blue",
	}

	b, err := msgpack.Marshal(&s)
	if err != nil {
		panic(err)
	}

	dec := msgpack.NewDecoder(bytes.NewReader(b))
	name, err := dec.DecodeString()
	if err != nil {
		panic(err)
	}
	fmt.Println("name", name)

	// Skip age.
	if err := dec.Skip(); err != nil {
		panic(err)
	}

	color, err := dec.DecodeString()
	if err != nil {
		panic(err)
	}
	fmt.Println("color", color)
}
```

**Comment by prashanthellina** [comment]
@vmihailenco Very nice! Thank you. I will check this out.

**Comment by prashanthellina** [comment]
@vmihailenco I realized after looking deeper that the above code snippet does not encode MyStruct as a map containing key values but as a sequence of values (without the keys). I can imagine writing code to take advantage of this facility (along with skip) but my use-case has an additional requirement.

I need to encode the struct as a map with keys and value within. Is there a way I can use the pattern you suggested along with this constraint. I imagine that might be some way to serialize the map with the keys in the same order as defined in the struct. Then, there could be a function to read values within the dict in order (by doing decodeString, Skip) etc.

**Comment by prashanthellina** [comment]
@vmihailenco Curious to see if you got around to reviewing my request. Thanks!

**Comment by vmihailenco** [comment]
Manually encoding map in msgpack is relatively easy - https://github.com/vmihailenco/msgpack/blob/master/map.go#L20-L33. I only need to export `encodeMapLen` and then you can write some highly-optimized functions to encode/decode your struct/map. Does that sound interesting?

**Comment by prashanthellina** [comment]
@vmihailenco Ah I see what you are saying. Yes please, that way I could write a function to encode a map while maintaining the sequence of keys. With that I could use Skip() to deserialize only some keys in the map.

**Comment by vmihailenco** [comment]
Done, see https://github.com/vmihailenco/msgpack/issues/63 for example
