### ISSUE TITLE
inconsistency in encoding of float32 inside a struct and when outside

### ISSUE THREAD

**Issue by algrebe** [vmihailenco/msgpack#59]
I've previously been using [github.com/ugorji/go/codec](https://github.com/ugorji/go/) and recently moved over to yours.

A normal float32 of value 0 gets encoded into `[202 0 0 0 0]` in both yours and ugorjis
But when inside a struct
```go
type TestStruct struct {
    MyFloat float32
}
```
When this gets encoded ( with MyFloat being 0), the value becomes `[129 163 78 117 109 203 0 0 0 0 0 0 0 0]`

The same on ugorji is `[129 163 78 117 109 202 0 0 0 0]`

There are two differences
1. extra 4 zeroes ( I'm not facing any issue with this but shouldn't it be 4 bytes instead of 8 ? )
2. The code 203 is being used instead of 202.

I'm having an issue with the second difference since decoding ugorji encodings with your decoder is causing it to panic 
```
failed to decode ugorji encoding...msgpack: invalid code ca decoding float64
	panic: msgpack: invalid code ca decoding float64
```

Here is a [detailed comparison](https://gist.github.com/algrebe/a021d9ce27cb8153d82f) to recreate the same.

**Comment by vmihailenco** [comment]
Fixed, thanks for the report!

**Comment by algrebe** [comment]
@vmihailenco thanks for the quick response !
