### ISSUE TITLE
Incorrect encoding of signed ints

### ISSUE THREAD

**Issue by mialinx** [vmihailenco/msgpack#61]
Briefly, this implementation of msgpack encodes signed ints always as negatives:
msgpack.Marshal(int(128)) => "d1 00 80"
Correct result is "cc 80"

I tested it with C, Rust msgpack implementations and they return "cc 80" for signed int 128.

Specification does not distinguish signed and unsigned int.
What they refer as uint8,uint16,uint32,uint64 is actualy "positive int value" with specified width
What they refer as int8,int16,int32,int64 is actualy "negative int value" with specified width

Original issue: https://github.com/tarantool/go-tarantool/issues/9

**Comment by vmihailenco** [comment]
Fixed, thanks for the report.
